[package]
name = "backrooms"
version = "0.1.0"
edition = "2021"

[dependencies]
glfw = { version = "0.59.0", features = ["vulkan"]}
ash = { version = "0.38.0+1.3.281", features = ["linked"]}
serde = {version = "1.0.218", features = ["derive"]}
serde_json = "1.0.139"
vk-mem = "0.4.0"